### ISSUE TITLE
Update docs and support empty `PropTypes`

### ISSUE THREAD

**Issue by coopy** [FormidableLabs/ecology#11]
1. Update the source prop docs to say `source={docgen.parse(require("!!raw!../src/components/ur-awsum-component"))`
2. Add support for empty PropTypes

**Comment by boygirl** [comment]
I think empty empty `PropTypes` is already supported in that you can leave off the source prop, and the prop table wont be rendered.

**Comment by coopy** [comment]
With the existing boilerplate component (with an `undefined` `Component.propTypes`), Ecology bombs: `api.js:24 Uncaught TypeError: Cannot convert undefined or null to object`
