### ISSUE TITLE
Include codemirror scripts+styles in bundle

### ISSUE THREAD

**Issue by coopy** [FormidableLabs/ecology#19]
...instead of script + link tags in `docs/index.html`.
Should be easy: https://www.npmjs.com/package/codemirror

**Comment by NogsMPLS** [comment]
Just a note on this, the initial error I get if I don't include CodeMirror as script in header refers to: https://github.com/FormidableLabs/component-playground/blob/master/src/components/editor.jsx#L6

which is what https://github.com/FormidableLabs/component-playground/issues/34 is referring to.

I'll submit a PR over there for this and move back to ecology once that has been updated/tagged.

**Comment by NogsMPLS** [comment]
https://github.com/FormidableLabs/component-playground/pull/55 should remove the need to add codemirror script in ecology once merged/tagged and ecology dependency updated.

**Comment by kylecesmat** [comment]
closed by https://github.com/FormidableLabs/component-playground/pull/55
